name: run-tests

on:
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js 12.14
        uses: actions/setup-node@v1
        with:
          node-version: 12.14
          
      - name: Install dependencies
        run: npm install

      - name: Run headless unit tests
        run: npm run test-headless

      - name: Run cypress e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run e2e
          browser: chrome
          headless: true
          wait-on: 'http://localhost:3000'
